compat: fix two return types
This fixes a build error introduced in 7d2b68df6301937a8299bca8bef135ae951b569c:
/include/linux/compat-2.6.25.h:172: error: two or more data types in declaration specifiers

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>